# ============================================================
# 数据入库配置
# ============================================================

CombineScoreProd:
  table_name: "data_score"
  db_url: "mysql+pymysql://prod:Abcd1234#@rm-bp1o6we7s3o1h76x1to.mysql.rds.aliyuncs.com:3306/data_prepared_new"
  chunk_size: 20000
  workers: 4
  private_keys:
    - "valuation_date"
    - "code"
    - "score_name"
  schema:
    valuation_date: { type: String, length: 50 }
    code: { type: String, length: 50 }
    score_name: { type: String, length: 50 }
    final_score: { type: Float }
    update_time: { type: DateTime }

CombineScoreTest:
  table_name: "combine_score_test"
  db_url: "mysql+pymysql://prod:Abcd1234#@rm-bp1o6we7s3o1h76x1to.mysql.rds.aliyuncs.com:3306/data_prepared_new"
  chunk_size: 20000
  workers: 4
  private_keys:
    - "valuation_date"
    - "code"
    - "score_name"
  schema:
    valuation_date: { type: String, length: 50 }
    code: { type: String, length: 50 }
    score_name: { type: String, length: 50 }
    final_score: { type: Float }
    update_time: { type: DateTime }
